FROM node:22-slim AS builder

WORKDIR /app

COPY frontend-ts/package.json frontend-ts/package-lock.json ./
RUN npm ci

COPY frontend-ts .
RUN npm run build


FROM nginx:alpine

COPY frontend-ts/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
