services:
  backend:
    build: ./backend-rs
    environment:
      ROCKET_ADDRESS: "0.0.0.0"
      ROCKET_PORT: "8000"
      LOS_ASSET_S3_BUCKET: ${LOS_ASSET_S3_BUCKET}
      LOCAL_ASSET_CACHE_ROOT: /cache
      LOS_ORTHOS_S3_PREFIX: ${LOS_ORTHOS_S3_PREFIX}
      LOS_TERRAIN_TILE_S3_PREFIX: ${LOS_TERRAIN_TILE_S3_PREFIX}
      LOS_OBSTRUCTION_S3_PREFIX: ${LOS_OBSTRUCTION_S3_PREFIX}
      NYC_DOB_SQLITE_DB_FILE: /data/nyc_dob.sqlite
      MESHDB_API_TOKEN: ${MESHDB_API_TOKEN}
      AWS_PROFILE: ${AWS_PROFILE}
    volumes:
      - ~/.aws:/root/.aws
      - asset-cache:/cache
      - ${NYC_DOB_SQLITE_DB_FILE}:/data/nyc_dob.sqlite:ro
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  frontend:
    build: ./frontend-ts
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy

volumes:
  asset-cache:
