[package]
name = "fresnel-2"
version = "0.1.0"
edition = "2024"

[dependencies]
derive-getters = "0.5.0"
image = "0.25.10"
rocket = { version = "0.5.1", features = ["json"] }
serde = "1.0.228"
aws-config = { version= "1.8.16", features = ["behavior-version-latest", "credentials-login"] }
aws-sdk-s3 = "1.111.0"
tokio = { version = "1", features = ["full"] }
typed-path = "0.12"
test-temp-dir = "0.7.0"
strum = "0.28.0"
strum_macros = "0.28"
derive-new = "0.7.0"
scopeguard = "1.2.0"
openjpeg-sys = "1.0.12"
eproj = "0.0.1-alpha.12"
approx = "0.5.1"
approx-derive = "0.2.8"
array2d = "0.3.2"
async-trait = "0.1"
tokio-rusqlite = "0.7.0"
#rusqlite = { version = "0.37.0", features = ["bundled"] }
wkt = "0.14.0"
arrayvec = "0.7.6"
tiff = "0.11.3"
geo = "0.33.1"


[dev-dependencies]
aws-smithy-mocks = "0.2.6"
aws-sdk-s3 = { version = "1", features = ["test-util"] }

[profile.dev]
debug = true
